// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzhgzhpjkgmdnvicwcpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6aGd6aHBqa2dtZG52aWN3Y3B0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDE5NTEsImV4cCI6MjA3Mjk3Nzk1MX0.2UIu6Wl9s6ViRkldZKlXRwgwCcmXuFVoM7ndIAuNiRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});